title: The Security Monk
description: > # this means to ignore newlines until "baseurl:"
  Welcome to My blog site. In this I'll be sharing my knowledge about particular topics and will update the same time to time.
permalink: ':title/'
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://www.yogendra-swaroop.tech/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Yogendra Swaroop Srivastava # add your name
author-img: index.png # add your photo
about-author: I am an Information Security Professional. Currently working at VirSec Systems as a Security Research Engineer. Previously worked at HackerU(India) as a Cyber Security Instructor(Red Team). I can make and break the code. My area of Interest lies in Application Security, Red teaming and Penetration Testing. # add description
social-twitter: yogendraswaroop # add your Twitter handle
social-facebook: yogendra.srivastava3 # add your Facebook handle
social-github: yogi1426 # add your Github handle
social-linkedin: yogendra-swaroop-srivastava-8aa45874/ # add your Linkedin handle
social-email: yogendra.swaroop.srivastava@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier
future: true
timezone: TIMEZONE
# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-gist

paginate: 8
paginate_path: "/page/:num"
google_analytics: UA-155255629-1
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
